### ISSUE TITLE
diff

### ISSUE THREAD

**Issue by jorgeboucas** [rbrands/MeetUpRoutes#70]
**Is your feature request related to a problem? Please describe.**

So far no single platform offers a route diff. Given the large number of overlapping routes out there this has become a need specially when building routes with others.

**Describe the solution you'd like**

In the backend a `diff` will in most cases suffice as most similar overlapping routes often have a common source and most waypoints will overlap.
On the front end 3 colors would display route A, B, and A common with B respectively. A small list like report of where A not equal to B would help route developers and users understand the differences. 

**Describe alternatives you've considered**

Download the routes, do a `diff` upload the differential. Far from being a great user experience.

**Comment by rbrands** [comment]
Thanks for your request. But MeetUpRoutes is intended to be used by a small group of authors to maintain a curated list of routes. MeetUpRoutes only stores pointers to external applications. Probably your request would be a good one for Komoot or so. Thx.
